name: CI
run-name: ${{ inputs.reason }}

on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - .sqlx/*
      - src/**/*
      - build.rs
      - Cargo.*
  pull_request:
    branches:
      - mistress
    paths:
      - .github/workflows/ci.yaml
      - .sqlx/*
      - src/**/*
      - build.rs
      - Cargo.*
  workflow_dispatch:
    inputs:
      reason:
        description: Dispatch reason
        type: string
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Run CI
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-toolchain:
          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up Rust problem matchers
        uses: catuhana/rust-problem-matchers@v1

      - name: Set-up or update Rust ${{ matrix.rust-toolchain }} toolchain
        run: rustup toolchain install ${{ matrix.rust-toolchain }} --profile default

      - name: Set-up Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Check code format
        run: cargo +${{ matrix.rust-toolchain }} fmt --verbose --all --check

      - name: Check code lint
        if: '!cancelled()'
        run: cargo +${{ matrix.rust-toolchain }} clippy --verbose -- -W clippy::nursery
